services:
  client:
    build:
      context: ./client # Change context to the client directory
      dockerfile: Dockerfile # The Dockerfile is now in the client directory
    ports:
      - "5173:5173" # Expose the port for Vite
    volumes:
      - ./client:/app # Mount the client directory
      - /app/node_modules
      # NOTE: Not mounting node_modules to prevent conflicts
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"] # Start the Vite development server
